---
name: Historian
description: Collects changes between two revisions
author: Memrise
inputs:
  token:
    description: GitHub API token, used for getting the list of commits
    required: true
    default: ${{ github.token }}
  since:
    description: Commit-ish to get changes since (defaults to the most recent release or tag)
  until:
    description: Commit-ish to get changes until (defaults to HEAD)
    default: HEAD
  chronological:
    description: Output changes in chronological order
    default: true
  slack template:
    description: |
      Message template to be used for line above the Slack output.

      Supports Markdown and makes the following variables available:

      - since.full
      - since.short
      - until.full
      - until.short

      Default: *Changes from {since.short} to {until.short}*
    default: '*Changes from {since.short} to {until.short}*'
outputs:
  plain-text:
    description: Changes listed in a plain-text format
  markdown:
    description: Changes listed in Markdown format
  slack:
    description: Changes prepared in a Slack-payload friendly format
runs:
  using: node16
  main: dist/index.js
